# Generated by Django 4.2 on 2023-04-20 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_subscriptions_alter_account_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='subscribers_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='subscriptions_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
